// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/user_service.proto

package pb

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for UserService service

func NewUserServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for UserService service

type UserService interface {
	// 测试
	TestUser(ctx context.Context, in *TestRequest, opts ...client.CallOption) (*TestResponse, error)
	// 用户注册
	UserRegister(ctx context.Context, in *RegisterRequest, opts ...client.CallOption) (*RegisterResponse, error)
	// 用户登录
	UserLogin(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*LoiginResponse, error)
	// 验证码
	GetCaptcha(ctx context.Context, in *CaptchaRequest, opts ...client.CallOption) (*CaptchaResponse, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) TestUser(ctx context.Context, in *TestRequest, opts ...client.CallOption) (*TestResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.TestUser", in)
	out := new(TestResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) UserRegister(ctx context.Context, in *RegisterRequest, opts ...client.CallOption) (*RegisterResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.UserRegister", in)
	out := new(RegisterResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) UserLogin(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*LoiginResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.UserLogin", in)
	out := new(LoiginResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetCaptcha(ctx context.Context, in *CaptchaRequest, opts ...client.CallOption) (*CaptchaResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.GetCaptcha", in)
	out := new(CaptchaResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	// 测试
	TestUser(context.Context, *TestRequest, *TestResponse) error
	// 用户注册
	UserRegister(context.Context, *RegisterRequest, *RegisterResponse) error
	// 用户登录
	UserLogin(context.Context, *LoginRequest, *LoiginResponse) error
	// 验证码
	GetCaptcha(context.Context, *CaptchaRequest, *CaptchaResponse) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) error {
	type userService interface {
		TestUser(ctx context.Context, in *TestRequest, out *TestResponse) error
		UserRegister(ctx context.Context, in *RegisterRequest, out *RegisterResponse) error
		UserLogin(ctx context.Context, in *LoginRequest, out *LoiginResponse) error
		GetCaptcha(ctx context.Context, in *CaptchaRequest, out *CaptchaResponse) error
	}
	type UserService struct {
		userService
	}
	h := &userServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&UserService{h}, opts...))
}

type userServiceHandler struct {
	UserServiceHandler
}

func (h *userServiceHandler) TestUser(ctx context.Context, in *TestRequest, out *TestResponse) error {
	return h.UserServiceHandler.TestUser(ctx, in, out)
}

func (h *userServiceHandler) UserRegister(ctx context.Context, in *RegisterRequest, out *RegisterResponse) error {
	return h.UserServiceHandler.UserRegister(ctx, in, out)
}

func (h *userServiceHandler) UserLogin(ctx context.Context, in *LoginRequest, out *LoiginResponse) error {
	return h.UserServiceHandler.UserLogin(ctx, in, out)
}

func (h *userServiceHandler) GetCaptcha(ctx context.Context, in *CaptchaRequest, out *CaptchaResponse) error {
	return h.UserServiceHandler.GetCaptcha(ctx, in, out)
}
