version: "3.3"
services:
  mysql:
    image: mysql:8.0
    container_name: mymysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test
      LANG: C.UTF-8
    volumes:
      - ./data:/var/lib/mysql
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    ports:
      - 3308:3306
    restart: unless-stopped
    privileged: true