version: "3.3"
services:
  redis:
    image: redis:latest
    container_name: myredis
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
      #  - /data/redis/redis.conf:/etc/redis/redis.conf
      - ./data:/data
    ports:
      - "0.0.0.0:6380:6379"
    restart: unless-stopped
    command: --requirepass "liujun"
    privileged: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
